### ISSUE TITLE
SSL Connections

### ISSUE THREAD

**Issue by LandyLane** [bbottema/java-socks-proxy-server#4]
If possible, seeing support for SSL connections via this server would be a nice feature as currently, the certificates prevent an HTTPS connection from being made.

**Comment by bbottema** [comment]
I've added support for this, but it seems oss.sonatype is having issues deploying new artifacts, so I can't release a new version 1.1.0 currently :/

**Comment by bbottema** [comment]
1.1.0 Released! You can now pass in your own `ServerSocketFactory` instance, such as a preconfigured `SSLServerSocketFactoryImpl`.

```
SocksServer socksServer = new SocksServer();
socksServer.start(300, myCustomServerSocketFactory);
```
